# Generated by Django 5.1.3 on 2025-03-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_location_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
    ]
