# Generated by Django 5.1.3 on 2025-03-08 19:11

import django.contrib.gis.db.models.fields
from django.db import migrations

# FIXME: When this attempts to migrate, I get:
#  ```
#  django.db.utils.ProgrammingError: cannot cast type bigint to geometry
#  ```


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_country_verbose_name_plural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
